[package]
name = "onlyserver"
version = "0.1.0"
authors = ["deadcodeonly <deadcodeonly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

iniparser = { path = "../iniparser" }